Repository Gyeongdan/gyeongdan-frontend, pull requests merged in 2024-07, with the labels that each got.

#6 커스텀 색상 추가 및 폰트 지정
  .github/workflows/pr_build_test.yml
  src/constants/color.ts
  src/constants/theme.ts
Labels: Design

#12 MUI 테마 색상 형식 문자열 버그 수정
  src/constants/theme.ts
Labels: Bug

#8 카테고리 탭 생성
  src/components/ColorTabs.tsx
  src/mocks/category.ts
Labels: Feature

#17 커스텀 색상 및 폰트 적용
  public/fonts.css
  src/constants/color.ts
  src/constants/theme.ts
Labels: Design

#19 헤더 구현
  src/components/Header.tsx
  src/mocks/category.ts
Labels: Feature

#23 Vercel 배포 설정
  .github/workflows/deploy-vercel.yml
Labels: Feature

#21 RootLayout 설정
  src/app/ClientThemeProvider.tsx
  src/app/favicon.ico
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.module.css
  src/app/page.tsx
Labels: Feature

#25 eslint 오류 해결
  .eslintrc.json
  package.json
  src/app/ClientThemeProvider.tsx
  src/app/page.tsx
  src/components/ColorTabs.tsx
  src/components/Header.tsx
  src/constants/theme.ts
  yarn.lock
Labels: Bug

#27 가로형 뉴스 카드 구현
  next.config.mjs
  src/components/NewsCardHorizontal.tsx
  src/constants/theme.ts
Labels: Feature

#30 그라데이션 배경 box 구현
  src/components/GradientBox.tsx
Labels: Feature

#32 기사 추천란 구현
  src/components/Suggestion.tsx
Labels: Feature

#34 뉴스레터 페이지 제작
  .eslintrc.json
  src/app/ClientThemeProvider.tsx
  src/app/layout.tsx
  src/app/newsletter/page.tsx
  src/app/page.tsx
  src/components/ColorTabs.tsx
  src/components/GradientBox.tsx
  src/components/Header.tsx
  src/components/NewsCardHorizontal.tsx
  src/constants/category.ts
  src/constants/color.ts
  src/constants/theme.ts
  src/mocks/category.ts
  src/mocks/news.ts
  src/mocks/suggestion.ts
Labels: Feature

#10 기사의 제목(헤드라인)을 표시하는 부분 생성
  src/components/Headline.tsx
  src/components/TagChip.tsx
  src/constants/color.ts
Labels: Feature

#37 CommentCard.tsx 생성
  public/image/sanjinee.png
  src/components/CommentCard.tsx
Labels: Feature

#39 로그인페이지 제작
  public/images/kakao_login.png
  src/app/login/page.tsx
  src/components/GradientBox.tsx
  src/components/Header.tsx
  src/constants/color.ts
Labels: Feature

#44 Noto Sans KR로 적용
  public/fonts.css
  src/components/NewsCardHorizontal.tsx
  src/constants/theme.ts
Labels: Design

#46 세로형 뉴스 카드 구현
  src/components/NewsCardVertical.tsx
Labels: Feature

#41 반응형 헤더 구현
  src/components/Header.tsx
Labels: Feature

#56 뉴스레터 전체 조회 api 연결
  package.json
  src/app/api/api.ts
  src/app/api/newsletter.ts
  src/app/newsletter/page.tsx
  src/components/NewsCardHorizontal.tsx
  src/constants/category.ts
  src/types.ts
  yarn.lock
Labels: API

#57 feat: 뉴스레터 지금 인기있는 기사 api 연결
  src/app/layout.tsx
  src/app/newsletter/page.tsx
  src/components/Suggestion.tsx
Labels: API

#42 기사 읽기 페이지 구현
  package.json
  public/images/sanjinee.png
  src/app/newsletter/[id]/page.tsx
  src/components/CommentCard.tsx
  src/components/Headline.tsx
  src/components/TooltipText.tsx
  src/constants/theme.ts
  src/mocks/article.ts
  yarn.lock
Labels: Feature

#51 세로형 뉴스 카드 이미지 선택으로 변경
  src/components/NewsCardVertical.tsx
Labels: Refactor

#54 유형 검사 페이지 제작
  src/app/test/page.tsx
  src/components/CommentCard.tsx
  src/mocks/test.ts
Labels: Feature

#64 유형 검사 질문 api 연결
  src/app/api/test.ts
  src/app/test/page.tsx
  src/types.ts
Labels: API

#67 로그인 post api 연결
  src/app/ClientThemeProvider.tsx
  src/app/Providers.tsx
  src/app/layout.tsx
  src/app/login/oauth2/code/kakao/page.tsx
  src/hooks/useGetUser.ts
  src/hooks/useGetWithToken.ts
  src/state/atom.ts
Labels: API

#70 code 로그 출력
  src/app/login/oauth2/code/kakao/page.tsx
Labels: Test

#72 로그인 버그 수정
  src/app/api/login.ts
Labels: Bug

#74 로그인 버그 수정
  src/app/api/login.ts
Labels: Bug

#60 인사이트 페이지 UI작업
  package.json
  src/app/api/api.ts
  src/app/insight/page.tsx
  src/components/ChartRenderer.tsx
  src/components/CommentCard.tsx
  src/components/NewsCardVertical.tsx
  src/constants/category.ts
  src/mocks/insight.ts
  src/mocks/insights.ts
  yarn.lock
Labels: Feature

#76 자료형 명시하도록 수정
  src/app/insight/page.tsx
  src/components/ChartRenderer.tsx
  src/mocks/insight.ts
  src/mocks/insights.ts
Labels: Bug

#79 헤더 카테고리 수정
  src/constants/category.ts
Labels: Design

#80 기사 조회 api 연결
  next.config.mjs
  src/app/api/newsletter.ts
  src/app/newsletter/[id]/page.tsx
  src/components/TooltipText.tsx
  src/types.ts
Labels: API

#84 유형 검사 결과 출력 api 연결
  src/app/api/test.ts
  src/app/test/page.tsx
  src/constants/userType.ts
Labels: API

#82 기사 조회 이미지 배율 조정
  src/app/newsletter/[id]/page.tsx
Labels: Design

#85 메인 페이지 리팩토링
  public/images/map.png
  src/app/about/mainpage.tsx
  src/app/about/page.tsx
  src/app/page.tsx
  src/components/FullpageComponent.tsx
  src/components/InfoSection.tsx
  src/constants/category.ts
  src/constants/main.ts
Labels: Refactor

#59 챗봇 UI작업
  src/app/chatbot/page.tsx
  src/app/insight/page.tsx
  src/components/ChatInput.tsx
  src/components/ChatMessage.tsx
  src/components/ChatbotContainer.tsx
  src/components/CommentCard.tsx
  src/mocks/chatIntro.ts
Labels: Feature

#90 지난 인사이트 클릭 시 인사이트 내용 바뀌도록 구현
  src/app/insight/page.tsx
  src/mocks/insights.ts
Labels: Feature

#89 인사이트&챗봇 페이지 레이아웃 디자인 수정
  src/app/chatbot/page.tsx
  src/app/insight/page.tsx
  src/components/ChatInput.tsx
  src/components/ChatbotContainer.tsx
  src/mocks/chatIntro.ts
Labels: Design

#94 유저 이름 조회 api 연결
  src/app/api/user.ts
  src/app/login/oauth2/code/kakao/page.tsx
  src/app/newsletter/page.tsx
  src/hooks/useGetWithToken.ts
  src/hooks/useMutateWithToken.ts
Labels: API

#96 유저 이름 조회 테스트
  src/app/api/user.ts
  src/app/newsletter/page.tsx
  src/hooks/useMutateWithToken.ts
Labels: Test

#99 api 코드 리팩토링
  src/app/api/api.ts
  src/app/api/newsletter.ts
  src/app/api/test.ts
  src/app/api/user.ts
  src/app/newsletter/page.tsx
  src/hooks/useMutateWithToken.ts
  src/state/atom.ts
Labels: Refactor

#93 헤더에서 경단 클릭 시 뉴스레터 페이지로 이동
  src/components/Header.tsx
Labels: Feature

#102 헤더에 프로필 구현
  src/app/newsletter/page.tsx
  src/components/Header.tsx
Labels: Feature

#101 사라지는 마을 UI 작업
  next.config.mjs
  package.json
  src/app/village/page.tsx
  src/components/KakaoMap.tsx
  src/constants/category.ts
  src/mocks/villages.ts
  src/types.ts
  yarn.lock
Labels: Feature

#105 로그인 후 원래 경로로 리다이렉션 구현
  src/app/Providers.tsx
  src/hooks/useCurrentPath.ts
Labels: Feature

#108 로그인 후 리다이렉션 버그 수정
  src/app/Providers.tsx
  src/components/Header.tsx
Labels: Bug

#110 잘못된 리다이렉트 경로 수정
  src/hooks/useCurrentPath.ts
Labels: Bug

#112 로그인 후 리다이렉트 테스트
  src/components/Header.tsx
  src/hooks/useCurrentPath.ts
Labels: Test

#115 유저 정보 상태 저장
  src/app/newsletter/page.tsx
  src/components/Header.tsx
  src/hooks/useCurrentPath.ts
  src/hooks/useGetUser.ts
  src/hooks/useUpdateUser.ts
  src/state/atom.ts
Labels: Feature

#118 뉴스 이미지 안불러와지는 버그 수정
  next.config.mjs
Labels: Bug

#119 로그인 시 헤더에 로그인 버튼 보이는 버그 수정
  src/hooks/useGetUser.ts
Labels: Bug

#127 VerticalCard 버그 픽스
  src/app/insight/page.tsx
  src/components/NewsCardVertical.tsx
Labels: Bug
